CREATE DATABASE FILEDOWN;

USE FILEDOWN;

CREATE TABLE archivos(
    ID varchar(50) AUTO_INCREMENT,
    TITULO varchar(50) NOT NULL,
    DESCRIPCION varchar(500) NOT NULL,
    RUTA_IMG varchar(500) NOT NULL,
    FORMATO_IMG varchar(50) NOT NULL,
    RUTA_ARCHIVO varchar(500) NOT NULL,
    FORMATO_ARCHIVO varchar(50) NOT NULL,
    FECHA_SUBIDA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE contacto(
    ID int(5) AUTO_INCREMENT,
    NOMBRE varchar(25) NOT NULL,
    CORREO varchar(50) NOT NULL,
    MENSAJE varchar(200) NOT NULL,
    PRIMARY KEY(ID)
);