CREATE DATABASE axtorrent CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE axtorrent;

CREATE TABLE users(
    ID int AUTO_INCREMENT,
    USERNAME varchar(50) NOT NULL,
    PASSWORD varchar(64) NOT NULL,
    ROLE int(2) NOT NULL DEFAULT 3,
    REGISTRATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LOGIN_DATE DATETIME,
    PRIMARY KEY(ID)
);

CREATE TABLE files(
    ID int AUTO_INCREMENT,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT,
    TYPE varchar(25) NOT NULL,
    GENRE TEXT,
    FORMAT varchar(25),
    DIRECTOR TEXT,
    CAST TEXT,
    EXT_IMG_ROUTE TEXT,
    INT_IMG_ROUTE varchar(500),
    IMG_FORMAT varchar(50),
    RELEASE_DATE int(5),
    UPLOAD_DATE DATETIME,
    USER_ID int DEFAULT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES users(ID)
);

CREATE TABLE episodes(
    ID int AUTO_INCREMENT,
    EPISODE TEXT,
    OUO_FILE_ROUTE TEXT,
    MAGNET_FILE_ROUTE TEXT,
    EXT_FILE_ROUTE TEXT,
    INT_FILE_ROUTE varchar(500),
    DATE DATETIME,
    FILE_ID int,
    PRIMARY KEY (ID),
    FOREIGN KEY (FILE_ID) REFERENCES files(ID)
);